### PR TITLE
updated with guida feedback

### PR DESCRIPTION
**Pull request by cryptodread**
Updated based on additions to the workflow and including the cost/benefit analysis deliverable.
Template needs to be created for deliverable.

### CODE REVIEW

**Comment by chrisguida** [comment]
Can you update the "cost/benefit anaylsis" box to be yellow as well as green? The champion should assist the engineer in making the cost/benefit analysis, since the champion is aware of the benefits, while the engineer is aware of the costs.

**Comment by cryptodread** [comment]
I put two-way arrows to show the support that the engineer is getting. Best practice is to have a single role be accountable for each box, or else you end up with confusion on who should be pushing an activity across the finish line.

there are a few exceptions to the rule like the "Green Light" box and "Hello World" box because they require two approvals.

**Comment by chrisguida** [comment]
In that case, I think this box should be yellow instead of green. The champion should be nagging the engineer, not the other way round.

**Comment by chrisguida** [comment]
Why was this closed?

**Pull request closed without merging**
